language: go
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false
go:
  - 1.7.x
  - 1.8.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
  
before_install:
  - go get github.com/mattn/goveralls
install:
  - 
script:
  - go get -t -v ./...
  - go tool vet .
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt
  after_success:
    - bash <(curl -s https://codecov.io/bash)
